# Generated by Django 4.1.7 on 2023-03-16 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapi', '0002_remove_commentaire_date_commentaire_cdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='cdate',
            field=models.DateField(blank=True, default=datetime.date(2023, 3, 16), null=True),
        ),
    ]
